#!/bin/bash

# Get the latest commit message
commit_msg=$(git log -1 --pretty=%B)

echo "Updating Heroku..."

cd tea_tracker || exit 1
# Check if working directory is clean
git pull heroku main || { echo "Failed to pull latest changes."; exit 1; }

git add .
git commit -m "Auto-sync from Repo A commit: $commit_msg"
git push heroku main --force

echo "Heroku updated."

# Check if the user is logged in to Heroku
if heroku auth:whoami > /dev/null 2>&1; then
    echo "Logged in to Heroku, proceeding with database update."

    # Try pushing the database
    if ! heroku pg:push tea_tracker_development DATABASE_URL --app tea-tracker; then
        echo "Failed to push data to Heroku. Resetting the database and retrying."
        heroku pg:reset --confirm tea-tracker
        heroku pg:push tea_tracker_development DATABASE_URL --app tea-tracker
        echo "Data pushed successfully after reset."
    else
        echo "Data pushed successfully to Heroku."
    fi

else
    echo "Not logged in to Heroku, skipping database update."
fi
