#!/bin/bash

echo "Running pre-push hook"
./githooks/run-brakeman
./githooks/run-tests

# $? stores exit value of the last command
if [ $? -ne 0 ]; then
 echo "Brakeman and Tests must pass before pushing!"
 exit 1
fi