#!/bin/bash
git config core.hooksPath githooks
chmod +x githooks/*
echo "Git hooks directory set to ./githooks"

GIT_DIR=$(git rev-parse --git-dir)

echo "Installing hooks..."
# ln -s ../../githooks/post-commit.bash $GIT_DIR/hooks/post-commit
ln -s ../../githooks/pre-commit.bash $GIT_DIR/hooks/pre-commit
ln -s ../../githooks/pre-push.bash $GIT_DIR/hooks/pre-push
echo "Done!"